name: Auto Process TXT Files

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行
  workflow_dispatch:      # 手动触发选项

jobs:
  process-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 允许文件提交

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create directories
      run: |
        mkdir -p scripts/input_files
        mkdir -p output
        mkdir -p unprocessed
        mkdir -p scripts/chinalist

    - name: Download TXT files
      run: |
        # 在此添加需要下载的TXT文件URL（示例）
        curl -L -o scripts/input_files/anti-ad-domains.txt https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/refs/heads/master/anti-ad-domains.txt
        curl -L -o scripts/input_files/adblockdomain.txt https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdomain.txt
        curl -L -o unprocessed/hagezi-domains-pro-yogadns.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.txt
        curl -L -o scripts/chinalist/dnscrypt-forwarding-rules.txt https://raw.githubusercontent.com/CNMan/dnscrypt-proxy-config/refs/heads/master/dnscrypt-forwarding-rules.txt
        
        # 显示下载文件列表（调试用）
        echo "下载文件列表:"
        ls -l scripts/input_files/

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run processing script
      run: |
        python scripts/process_files.py \
          --input "scripts/input_files/*.txt" \
          --output output/processed.txt
        
        # 显示处理结果（调试用）
        echo "===== 处理前原始文件 ====="
        head scripts/input_files/*.txt
        echo "===== 处理后输出文件 ====="
        cat output/processed.txt
